"""add scan_cache, drop scan_run.payload

Revision ID: 3bcc233e81c3
Revises: 6aa891b8b79d
Create Date: 2026-04-25 20:42:46.766110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcc233e81c3'
down_revision: Union[str, Sequence[str], None] = '6aa891b8b79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_cache',
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('candidates_count', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('scan_type')
    )
    with op.batch_alter_table('scan_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_cache_run_at'), ['run_at'], unique=False)

    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.drop_column('payload')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', sa.TEXT(), nullable=True))

    with op.batch_alter_table('scan_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_cache_run_at'))

    op.drop_table('scan_cache')
    # ### end Alembic commands ###
