"""baseline schema

Revision ID: 4f9d5582ae62
Revises: 
Create Date: 2026-04-25 19:08:19.145334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9d5582ae62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capital_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capital_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capital_events_date'), ['date'], unique=False)

    op.create_table('daily_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_bar_symbol_date')
    )
    with op.batch_alter_table('daily_bars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_bars_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_bars_symbol'), ['symbol'], unique=False)

    op.create_table('instrument_meta',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market_cap_rs', sa.Float(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('instrument_prices',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('yf_suffix', sa.String(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('kite_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_token', sa.Integer(), nullable=False),
    sa.Column('exchange_token', sa.Integer(), nullable=False),
    sa.Column('tradingsymbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('instrument_type', sa.String(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kite_instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kite_instruments_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_kite_instruments_instrument_token'), ['instrument_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_kite_instruments_tradingsymbol'), ['tradingsymbol'], unique=False)

    op.create_table('market_breadth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('universe', sa.String(), nullable=False),
    sa.Column('total_stocks', sa.Integer(), nullable=False),
    sa.Column('advances', sa.Integer(), nullable=False),
    sa.Column('declines', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('new_highs_52w', sa.Integer(), nullable=False),
    sa.Column('new_lows_52w', sa.Integer(), nullable=False),
    sa.Column('pct_above_20ema', sa.Float(), nullable=False),
    sa.Column('pct_above_50ema', sa.Float(), nullable=False),
    sa.Column('pct_above_200ema', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'universe', name='uq_breadth_date_universe')
    )
    with op.batch_alter_table('market_breadth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_breadth_date'), ['date'], unique=False)

    op.create_table('masterlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'value', name='uq_category_value')
    )
    with op.batch_alter_table('masterlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_masterlist_items_category'), ['category'], unique=False)

    op.create_table('scan_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('candidates_count', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('bars_refreshed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_run_run_at'), ['run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_run_scan_type'), ['scan_type'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_no', sa.Integer(), nullable=True),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('option_type', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('initial_entry_price', sa.Float(), nullable=False),
    sa.Column('initial_qty', sa.Integer(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=False),
    sa.Column('tsl', sa.Float(), nullable=True),
    sa.Column('cmp', sa.Float(), nullable=True),
    sa.Column('charges_rs', sa.Float(), nullable=True),
    sa.Column('setup', sa.String(), nullable=True),
    sa.Column('base_duration', sa.String(), nullable=True),
    sa.Column('plan_followed', sa.Boolean(), nullable=True),
    sa.Column('exit_trigger', sa.String(), nullable=True),
    sa.Column('proficiency', sa.String(), nullable=True),
    sa.Column('growth_areas', sa.String(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_instrument'), ['instrument'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('setup_label', sa.String(), nullable=True),
    sa.Column('alert_price', sa.Float(), nullable=True),
    sa.Column('suggested_sl', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_symbol'), ['symbol'], unique=True)

    op.create_table('exits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exits_trade_id'), ['trade_id'], unique=False)

    op.create_table('imported_executions',
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('applied_to_trade_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applied_to_trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    with op.batch_alter_table('imported_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imported_executions_symbol'), ['symbol'], unique=False)

    op.create_table('pyramids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pyramids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pyramids_trade_id'), ['trade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyramids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pyramids_trade_id'))

    op.drop_table('pyramids')
    with op.batch_alter_table('imported_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_executions_symbol'))

    op.drop_table('imported_executions')
    with op.batch_alter_table('exits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exits_trade_id'))

    op.drop_table('exits')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_symbol'))

    op.drop_table('watchlist')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.drop_index(batch_op.f('ix_trades_instrument'))
        batch_op.drop_index(batch_op.f('ix_trades_entry_date'))

    op.drop_table('trades')
    op.drop_table('settings')
    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_run_scan_type'))
        batch_op.drop_index(batch_op.f('ix_scan_run_run_at'))

    op.drop_table('scan_run')
    with op.batch_alter_table('masterlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_masterlist_items_category'))

    op.drop_table('masterlist_items')
    with op.batch_alter_table('market_breadth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_breadth_date'))

    op.drop_table('market_breadth')
    with op.batch_alter_table('kite_instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kite_instruments_tradingsymbol'))
        batch_op.drop_index(batch_op.f('ix_kite_instruments_instrument_token'))
        batch_op.drop_index(batch_op.f('ix_kite_instruments_exchange'))

    op.drop_table('kite_instruments')
    op.drop_table('instrument_prices')
    op.drop_table('instrument_meta')
    with op.batch_alter_table('daily_bars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_bars_symbol'))
        batch_op.drop_index(batch_op.f('ix_daily_bars_date'))

    op.drop_table('daily_bars')
    with op.batch_alter_table('capital_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capital_events_date'))

    op.drop_table('capital_events')
    # ### end Alembic commands ###
